app_user_video:
    resource: "@AppBundle/Resources/config/routing/video.yml"
    prefix:   /user/video

mewpipe_index:
    path:      /
    defaults:  { _controller: AppBundle:Index:index }

mewpipe_search:
    path:      /search
    defaults:  { _controller: AppBundle:Index:search }
    requirements:
        _method:  GET

mewpipe_video_list:
    path:      /most/{type}
    defaults:  { _controller: AppBundle:Video:viewList }

mewpipe_view_video:
    path:      /video/{id}
    defaults:  { _controller: AppBundle:Video:view }

mewpipe_view_video_link:
    path:      /video/link/{hash}
    defaults:  { _controller: AppBundle:Video:viewLink }
