<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VideoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideoRepository extends EntityRepository
{
    public function mostViewed($limit = null)
    {
        $qb = $this->createQueryBuilder('v')
            ->where("v.status <> 'link'")
            ->orderBy('v.viewCount', 'DESC');

        if($limit != null)
            $qb->setMaxResults($limit);

        return $qb->getQuery()->getResult();
    }

    public function mostShared($limit = null)
    {
        $qb = $this->createQueryBuilder('v')
            ->where("v.status <> 'link'")
            ->orderBy('v.shareCount', 'DESC');

        if($limit != null)
            $qb->setMaxResults($limit);

        return $qb->getQuery()->getResult();
    }

    public function mostRecent($limit = null)
    {
        $qb = $this->createQueryBuilder('v')
            ->where("v.status <> 'link'")
            ->orderBy('v.addedDate', 'DESC');

        if($limit != null)
            $qb->setMaxResults($limit);

        return $qb->getQuery()->getResult();
    }

    public function searchVideo($text)
    {
        $qb = $this->createQueryBuilder('v')
            ->where('v.title LIKE :text')
            ->andWhere("v.status <> 'link'")
            ->setParameter('text', '%'.$text.'%')
            ->orderBy('v.title');

        return $qb->getQuery()->getResult();
    }
}
